"""Render brain.db facts into the wiki as a generated, human-browsable view.

projects/<slug>.md            facts of one repo, grouped by kind
failures/<kind>.md            global pitfalls / corrections / procedures / facts / ...
identity/preferences.md       global preferences
identity/people.md            global person facts
index.md                      page list with counts

Pages are capped at MAX_PAGE bytes; bigger groups paginate (<name>-2.md, -3.md, ...) so the view
stays lossless. skills/, changelog.md and other hand-written files are never touched. Generated
pages that no longer have facts are removed (they remain in git history).
"""

import logging
import subprocess
import time
from collections import defaultdict
from pathlib import Path

from .brain import KINDS, Brain

logger = logging.getLogger("cc-brain")

MAX_PAGE = 25 * 1024
GENERATED_DIRS = ("projects", "failures", "identity")
MARK = "<!-- generated by `cc-brain render` from ~/.cc-brain/brain.db — change facts with recall/remember/correct, not here -->"
KIND_TITLES = {
    "pitfall": "Pitfalls", "correction": "Corrections", "decision": "Decisions", "preference": "Preferences",
    "procedure": "Procedures", "person": "People", "fact": "Facts", "note": "Notes",
}


def _page_for(row):
    if row["project"] and row["project"] != "global":
        return f"projects/{row['project']}"
    if row["kind"] == "preference":
        return "identity/preferences"
    if row["kind"] == "person":
        return "identity/people"
    return f"failures/{row['kind']}"


def _line(row):
    day = time.strftime("%Y-%m-%d", time.localtime(row["last_seen"] or row["updated"]))
    star = " ★" if row["importance"] >= 3 else ""
    return f"- {row['text']} _(#{row['id']}, {day}{star})_\n"


def _rank(row):
    return (-row["importance"], -(row["last_seen"] or row["updated"] or 0))


def _paginate(base, title, rows, grouped):
    """Yield (relpath, text) pages, each <= MAX_PAGE bytes."""
    if grouped:
        by_kind = defaultdict(list)
        for r in rows:
            by_kind[r["kind"]].append(r)
        sections = [(KIND_TITLES[k], sorted(by_kind[k], key=_rank)) for k in KINDS if by_kind.get(k)]
    else:
        sections = [(None, sorted(rows, key=_rank))]

    pages, cur, n = [], [], 1

    def header(n):
        suffix = f" (part {n})" if n > 1 else ""
        return f"{MARK}\n# {title}{suffix}\n\n"

    size = len(header(1).encode())
    for sec_title, sec_rows in sections:
        head = f"\n## {sec_title}\n\n" if sec_title else ""
        for i, r in enumerate(sec_rows):
            line = _line(r)
            add = (head if i == 0 or not cur else "") + line
            if size + len(add.encode()) > MAX_PAGE - 200 and cur:
                pages.append(cur)
                cur, n = [], n + 1
                size = len(header(n).encode())
                add = head + line if head else line
            cur.append(add)
            size += len(add.encode())
    if cur:
        pages.append(cur)
    total = len(pages)
    for i, body in enumerate(pages, 1):
        rel = f"{base}.md" if i == 1 else f"{base}-{i}.md"
        nav = f"\n_Page {i} of {total}" + (f" — next: `{base}-{i + 1}.md`_\n" if i < total else "_\n") if total > 1 else ""
        yield rel, header(i) + "".join(body) + nav


def render(config, brain=None, commit=True):
    brain = brain or Brain(config["brain_db"], config)
    wiki = Path(config.get("wiki_dir", str(Path.home() / "llm-wiki"))).expanduser()
    groups = defaultdict(list)
    for r in brain.live_facts():
        groups[_page_for(r)].append(r)

    written = {}
    for base, rows in groups.items():
        if base.startswith("projects/"):
            title, grouped = f"{base.split('/', 1)[1]} — project memory", True
        elif base.startswith("identity/"):
            title, grouped = base.split("/", 1)[1].capitalize(), False
        else:
            title, grouped = f"Global {KIND_TITLES.get(base.split('/', 1)[1], base)}", False
        for rel, text in _paginate(base, title, rows, grouped):
            written[rel] = (text, len(rows))

    # remove generated-dir pages that are no longer produced (lossless: facts live in brain.db, history in git)
    removed = []
    for d in GENERATED_DIRS:
        for md in (wiki / d).glob("*.md"):
            rel = str(md.relative_to(wiki))
            if rel not in written:
                md.unlink()
                removed.append(rel)

    changed = 0
    for rel, (text, _) in written.items():
        p = wiki / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        if not p.exists() or p.read_text(errors="replace") != text:
            p.write_text(text)
            changed += 1

    index = [f"{MARK}\n# Brain index\n\nQuery with the cc-brain MCP: `recall`, `timeline`, `wiki_search`. "
             "Hand-written docs live in `skills/`.\n"]
    for d in GENERATED_DIRS:
        rels = sorted(r for r in written if r.startswith(d + "/"))
        if rels:
            index.append(f"\n## {d}\n\n")
            index += [f"- [{r}]({r}) — {written[r][1]} facts\n" if not r.rsplit("-", 1)[-1][:-3].isdigit()
                      else f"- [{r}]({r})\n" for r in rels]
    skills = sorted(str(p.relative_to(wiki)) for p in (wiki / "skills").glob("*.md"))
    if skills:
        index.append("\n## skills (hand-written)\n\n")
        index += [f"- [{r}]({r})\n" for r in skills]
    idx = "".join(index)
    old_idx = (wiki / "index.md").read_text(errors="replace") if (wiki / "index.md").exists() else ""
    if old_idx != idx:
        (wiki / "index.md").write_text(idx)

    stats = {"pages": len(written), "changed": changed, "removed": len(removed),
             "max_page_kb": round(max(len(t.encode()) for t, _ in written.values()) / 1024, 1)}
    if commit and (wiki / ".git").exists():
        subprocess.run(["git", "-C", str(wiki), "add", "-A"], capture_output=True)
        res = subprocess.run(["git", "-C", str(wiki), "commit", "-qm",
                              f"render: {stats['pages']} pages, {changed} changed, {len(removed)} removed"],
                             capture_output=True, text=True)
        stats["committed"] = res.returncode == 0
    logger.info("render: %s", stats)
    return stats
